[package]
name = "r3"
version = "0.0.1"
authors = ["Eduard-Mihai Burtescu <edy.burt@gmail.com>"]

[dependencies]
regex = "*"
regex_macros = "*"
image = "*"

[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"

[dependencies.pistoncore-glutin_window]
git = "https://github.com/PistonDevelopers/glutin_window"

[dependencies.piston2d-graphics]
git = "https://github.com/PistonDevelopers/graphics"

[dependencies.glium]
git = "https://github.com/tomaka/glium"
features = ["image"]
default_features = false

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs"

[dependencies.pistoncore-window]
git = "https://github.com/PistonDevelopers/window"

[dependencies.shader_version]
git = "https://github.com/PistonDevelopers/shader_version"

[dependencies.piston-shaders_graphics2d]
git = "https://github.com/PistonDevelopers/shaders"

[[bin]]
name = "rid3"
